services:
  db:
    container_name: kuali-db
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./backend/.env
    volumes:
      - ./prisma/init.sh:/docker-entrypoint-initdb.d/init.sh
      - kuali-data:/var/lib/mysql
    networks:
      - backend-network
  backend:
    container_name: kuali-backend
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=mysql://root:root@kuali-db:3306/kuali
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - backend-network

volumes:
  kuali-data:

networks:
  backend-network:
    driver: bridge