# backend/Dockerfile.prod
FROM node:lts-alpine3.20 AS builder

WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./
COPY tsconfig.json ./

# Instalar dependencias
RUN npm ci --only=production && npm cache clean --force

# Copiar código fuente
COPY . .

# Generar archivos de Prisma (esto creará la carpeta generated)
RUN npx prisma generate

# Compilar TypeScript (si usas TypeScript)
RUN npm run build

# Etapa de producción
FROM node:lts-alpine3.20 AS production

WORKDIR /app

# Copiar archivos de configuración
COPY --from=builder /app/package*.json ./

# Copiar código compilado
COPY --from=builder /app/build ./build
# O si no usas TypeScript, copia el código fuente:
# COPY --from=builder /app/src ./src

# Copiar otros archivos necesarios
COPY --from=builder /app/src/generated ./build/src/generated

# Instalar dependencias
RUN npm ci --only=production && npm cache clean --force

# # Crear usuario no-root
# RUN addgroup -g 1001 -S nodejs
# RUN adduser -S nodejs -u 1001

# # Cambiar ownership de archivos
# RUN chown -R nodejs:nodejs /app
# USER nodejs

EXPOSE 3000

CMD ["npm", "start"]
# CMD ["tail", "-f", "/dev/null"]