# backend/Dockerfile.prod
FROM node:lts-alpine3.20 AS builder

WORKDIR /app

# Copiar archivos de configuración
COPY package*.json ./
COPY tsconfig.json ./

# Instalar dependencias
RUN npm ci --only=production && npm cache clean --force

# Copiar código fuente
COPY . .

# Generar archivos de Prisma (esto creará la carpeta generated)
RUN npx prisma generate

# Compilar TypeScript (si usas TypeScript)
RUN npm run build

# Etapa de producción
FROM node:lts-alpine3.20 AS production

WORKDIR /app

# Copiar archivos de configuración
COPY --from=builder /app/package*.json ./

# Copiar código compilado
COPY --from=builder /app/build ./

# Copiar otros archivos necesarios
COPY --from=builder /app/src/generated ./src/generated

COPY --from=builder /app/.env.prod ./.env

COPY --from=builder /app/prisma ./prisma

# Instalar dependencias
RUN npm ci --only=production && npm cache clean --force

EXPOSE 3000

CMD ["npm", "start"]
