export const assignedStudents = [
  {
    user_id: 1,
    name: 'Juan',
    second_name: 'Pi',
    paternal_lastname: 'Apellido',
    maternal_lastname: 'Apellido2',
    institutional_email: 'usuario@dominio.com',
    personal_email: '',
    curp: '',
    identifier: 'IPN000001',
    role: {
      role_id: 1,
      name: 'ESTUDIANTE',
    },
    academic_programs_as_student: [],
  },
  {
    user_id: 2,
    name: 'Diego',
    second_name: 'Sahid',
    paternal_lastname: 'Apellido',
    maternal_lastname: 'Apellido2',
    institutional_email: 'usuario@dominio.com',
    personal_email: '',
    curp: '',
    identifier: 'IPN000002',
    role: {
      role_id: 1,
      name: 'ESTUDIANTE',
    },
    academic_programs_as_student: [],
  },
  {
    user_id: 3,
    name: 'Erick',
    second_name: 'A',
    paternal_lastname: 'Apellido',
    maternal_lastname: 'Apellido2',
    institutional_email: 'usuario@dominio.com',
    personal_email: '',
    curp: '',
    identifier: 'IPN000003',
    role: {
      role_id: 1,
      name: 'ESTUDIANTE',
    },
    academic_programs_as_student: [],
  },
]
